### PR TITLE
 Add request parameter to filename generator

### PR DESCRIPTION
**Pull request by ddabble**
This enables users to have additional information at hand when generating filenames, like using `request.user` or any of the request's HTTP headers - `HTTP_REFERER` in particular, e.g. for naming/placing files per app.

### CODE REVIEW

**Comment by matthiask** [comment]
Thank you!

I'm not sure whether that's wanted (I don't have strong opinions either way) and, not being a user of the uploader part myself, probably will not merge this PR. Still, some comments:

- You should add tests for this
- The `TypeError` isn't raised just because you pass a request instead of an user instance -- the argument count is the same. You might want to inspect the generator's arguments using https://docs.python.org/3/library/inspect.html and raise deprecation warnings when a generator still expects an user instead of a request to preserve backwards compatibility for a time.

**Comment by ddabble** [comment]
Nevermind my last question, I moved my test code into a new file, `tests/test_deprecation.py`, to match the rest of the tests.

**Comment by javinievas** [comment]
I also need this feature to organize files in folders per user (to avoid naming conflicts with other files that you do not own)
Are you planning to merge this soon?

**Comment by matthiask** [comment]
Thanks!

**Pull request merged**
