### PR TITLE
hard-coding of ckeditor.js (again!) *grmbl*

### PR DESCRIPTION
**Pull request by macolo**
See https://github.com/django-ckeditor/django-ckeditor/issues/192 - its just not going to work with `ManifestStaticFilesStorage` etc.!

### CODE REVIEW

**Comment by matthiask** [comment]
It does work with ``ManifestStaticFilesStorage``, you just have to set ``CKEDITOR_BASEPATH`` (as I've already written a few weeks ago in #346).

I have opened a pull request with a documentation patch (#376).

**Comment by riklaunim** [comment]
I assume this isn't needed any more?

**Comment by Flimm** [comment]
Sorry, @riklaunim, but it still doesn't work. See my comment in pull request #377 .

**Comment by matthiask** [comment]
Thank you!

I'm working on getting this fixed (for real) without reverting to the old behavior, therefore I'm rejecting this PR. Thanks anyway, and looking forward to your next contribution.

**Pull request closed without merging**
