### PR TITLE
Django 2.0 compatibility

### PR DESCRIPTION
**Pull request by ahumeau**

### CODE REVIEW

**Comment by ahumeau** [comment]
You're welcome.
Do you have any idea of when a new PyPI release is planned?

**Comment by matthiask** [comment]
No, maybe @riklaunim can answer this.

**Comment by riklaunim** [comment]
If there won't be anything hanging I can release it very soon :)

**Comment by mattandrews** [comment]
I need this too :)

**Comment by riklaunim** [comment]
New version is up

**Pull request merged**
