### PR TITLE
allows uploads to be prefixed by any adhoc property on the user, not just the username

### PR DESCRIPTION
**Pull request by sbussetti**
Pretty minor change, just allows you to specify the upload folder prefix to be any property or callable on the user model.

### CODE REVIEW

**Comment by riklaunim** [comment]
And some refactors along the way too. It could be more than one commit.

**Comment by sbussetti** [comment]
Kinda? -- needed to clean up how settings were handled in order to easily provide backwards compat to the existing CKEDITOR_RESTRICT_BY_USER field.

**Comment by sbussetti** [comment]
Sorry, could you clarify?  Should this be broken  out into multiple commits? And if so how, how would you like the changes to be organized?

**Comment by riklaunim** [comment]
In general it should be. First a refactor, then a change.

There are returning issues/pull request about making file upload bigger / more generic and so on. From one side it's cool to have better features or more flexible app, but on the other hand ckeditor field application is becoming a full blown CMS-field application. I can merge this one (if you split it then even better), but expect that some bigger changes make take place in the (closer) future.

**Comment by sbussetti** [comment]
Thanks for explaining the context; I'll modify my changes and break things
up.

**Comment by matthiask** [comment]
@sbussetti Do you still intend to work on this?

**Comment by sbussetti** [comment]
@matthiask holy christmas, I completely forgot about this one.  Let me add it to my todo list.  If you don't see an update to this pull within in a week, feel free to close it out.

**Comment by sbussetti** [comment]
@matthiask okay, let me know if this (much more targeted) change looks okay to you and if so I can write a test to go along with it.

**Comment by matthiask** [comment]
Looks good! A minimal documentation update would be awesome as well.

**Comment by sbussetti** [comment]
@matthiask done and done

**Comment by riklaunim** [comment]
looks good to me.

**Comment by matthiask** [comment]
Thank you!

**Pull request merged**
