### PR TITLE
csrf_exempt on image upload

### PR DESCRIPTION
**Pull request by hcastilho**
Solves #84

### CODE REVIEW

**Comment by riklaunim** [comment]
And how does it solves it?

**Comment by hcastilho** [comment]
Didn't check to see why csrf_exempt is not applied correctly as I had some hurry in getting this to work.
I will try to reproduce it later and find out what is going on.

**Comment by hcastilho** [comment]
Just a coincidence apparently.
I'm now unable to reproduce the issue.

**Comment by riklaunim** [comment]
I suspect it might be something with iframe and cookies.

**Comment by hcastilho** [comment]
Are you able to reproduce it reliably?

**Comment by riklaunim** [comment]
nope, not at the moment

**Pull request closed without merging**
