### PR TITLE
Update CKEditor to 4.8.0

### PR DESCRIPTION
**Pull request by daenub**
Update the CKEditor bundle from version 4.7.3 to 4.8.0.

### CODE REVIEW

**Comment by riklaunim** [comment]
Is this the full package?

**Comment by matthiask** [comment]
The full package would not have this many plugins removed.

Please also update the CHANGELOG and the README. Here's the shortest example I could find:
https://github.com/django-ckeditor/django-ckeditor/commit/6a9516b5e88117d957b88ec284a803871d47c339

Thanks :)

**Comment by daenub** [comment]
@riklaunim 
I used the `build-config.js` of the previous version. So it should be the same package.

@matthiask 
I've now updated the CHANGELOG and the README too.
I already removed the `samples` folder from the CKEditor in my first commit. Where did you see it?

**Comment by riklaunim** [comment]
build-config.js likely doesn't contain some specific extras. To be checked.

**Comment by daenub** [comment]
@riklaunim 
I've now included the full ckeditor package.

**Comment by riklaunim** [comment]
Closing this one as we are on 4.9.2

**Pull request closed without merging**
