### PR TITLE
update to ckeditor 4.5.3 and others

### PR DESCRIPTION
**Pull request by luzfcb**
* Updated ckeditor to 4.5.3 (from https://github.com/ckeditor/ckeditor-dev/tree/4.5.3)
* Added new plugins from ckeditor maintainers: adobeair, ajax, autoembed, autogrow, autolink, bbcode, codesnippet, codesnippetgeshi, devtools, divarea, docprops, embed, embedbase, embedsemantic, filetools, iframedialog, image2, language, lineutils, mathjax, menubutton, notification, notificationaggregator, placeholder, sharedspace, sourcedialog, stylesheetparser, tableresize, uicolor, uploadimage, uploadwidget, widget, xml 
* Add `zip_safe=False` on setup config, to force does not create ".egg" file 
* Add python Wheel package configuration
* Add setup.py functions to easy release ".egg" package and Wheel package, and tag version on git ( ``python setup.py publish`` and ``python setup.py tag`` )
* Improved Tox configuration to code coverage check, code quality check (flake8), imports order check (isort) and test with django master branch
* Add code quality configurations
* Add EditorConfig configuration file
* Refactored code to be in compliance with PEP8

### CODE REVIEW

**Comment by riklaunim** [comment]
Nice one, thanks!

**Comment by luzfcb** [comment]
:dancers:  My next challenge will be to figure out how to create read-only sections...( any suggestion ??)

Oh... I forgot add me in autors.rst

**Comment by riklaunim** [comment]
read-only? within text editor?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by luzfcb** [comment]
@riklaunim yes
I'm trying to make a generic pluggable document editor, https://github.com/luzfcb/django_documentos ( I am still far from having anything useful ), I will need to create document templates, which will initially have, header and footer with some non-editable sections.

the company I work has a legacy system (which has not been developed by her), which has this functionality. however, it was developed with ckeditor 2, and I only have minified code.

**Comment by riklaunim** [comment]
It either would have to be CKEditor-only code with some django data input (templates as json or something) or maybe some NoSQL schema-free database and prototyping a Django form based on the template (a.k.a moving the logic above ckeditor).

**Pull request merged**
