### PR TITLE
Fix missing `widget` context variable

### LINKED ISSUE #706: Missing `widget` context variable
After merging #698, an issue arose when using `CKEditorWidget` in a `MultiWidget` (specifically from [this line](https://github.com/django/django/blob/4.0.3/django/forms/widgets.py#L905)), where an error would be raised due to [`CKEditorWidget.get_context()`](https://github.com/django-ckeditor/django-ckeditor/blob/6.3.0/ckeditor/widgets.py#L103-L119) not returning a `widget` context variable - like all of Django's widgets seem to do.

A solution could be including the context from the superclass ([`Widget.get_context()`](https://github.com/django/django/blob/4.0.3/django/forms/widgets.py#L261-L271)) in the dictionary returned by [`CKEditorWidget.get_context()`](https://github.com/django-ckeditor/django-ckeditor/blob/6.3.0/ckeditor/widgets.py#L113-L119).

### PR DESCRIPTION
**Pull request by ddabble**
This resolves #706.

This PR also includes some other minor improvements - some necessary for the tests, others just for cleanup. See the commit messages for details.

### CODE REVIEW

**Review by matthiask — COMMENTED** [review]
I'm not sure if I understand correctly, but `deprecated_context` is only there for the benefit of people who have overridden (or replaced) the `ckeditor/widget.html` template in their project, is that correct?

So the best way to proceed may be to push a patch release now, remove this context afterwards and release 7.x or 6.4.x in the future?

The changes look good to me.

**Comment by ddabble** [comment]
> I'm not sure if I understand correctly, but `deprecated_context` is only there for the benefit of people who have overridden (or replaced) the `ckeditor/widget.html` template in their project, is that correct?

Yes, I could have made that more clear, but that was the intention.

> So the best way to proceed may be to push a patch release now, remove this context afterwards and release 7.x or 6.4.x in the future?

That sounds like a good plan to me!

**Comment by matthiask** [comment]
Great, thanks for confirming this. 

I have released 6.3.1 containing these changes. Thanks!

**Comment by matthiask** [comment]
@ddabble I'm sorry to report that this change broke things. The CKEditor widget was always overridden by the default textarea widget (see #708)

It works again and a bugfix release has already been published. The multiwidget test is an expected failure if you want to take a look https://github.com/django-ckeditor/django-ckeditor/blob/741dca6bf30616e92511213967b15ce6e8951e38/ckeditor_demo/demo_application/tests/test_widget_context.py#L84-L85 -- I wasn't able to fix it without spending more time than I wanted to on this today. I hope you can take a look! 

Thanks (no hard feelings at all!)

**Comment by ddabble** [comment]
@matthiask No problem, I can take a look at it! 😊

The failing test is caused by forcing the `widget` keyword argument in the form fields (specifically [here](https://github.com/django-ckeditor/django-ckeditor/blob/73848b4f3f10eb42e6ad60550bb2729b27f6fdc0/ckeditor/fields.py#L34) and [here](https://github.com/django-ckeditor/django-ckeditor/blob/73848b4f3f10eb42e6ad60550bb2729b27f6fdc0/ckeditor_uploader/fields.py#L22)), btw.
I can (re)make a fix for that as well, as it's generally not expected that keyword arguments are ignored when calling a method or instantiating a class (e.g. `RichTextFormField(widget=CkEditorMultiWidget)`) 🙂

**Pull request merged**
