### PR TITLE
Custom filebrowser url

### PR DESCRIPTION
**Pull request by ikresoft**
Support for custom filebrowser.

### CODE REVIEW

**Comment by riklaunim** [comment]
So if you add those URLs before that code it won't add those from reverse. Did you used other filebrowser that is publicly available?

**Comment by ikresoft** [comment]
Yes, I make my own, which is globaly django-url-browser which can browse django filer images, files and all urlnames.
https://github.com/ikresoft/django-url-browser

I have to finish documentation for this project and few screenshots.

**Comment by ikresoft** [comment]
Anyway you should allow ckeditor to use custom settings like filebrowser or fileupload.

**Comment by riklaunim** [comment]
Yes. Can you also add a note in the readme about this feature?

**Pull request merged**
