### PR TITLE
Fix regression - lib works again for Django 1.8--1.10. Cleanup tests.

### PR DESCRIPTION
**Pull request by dekoza**
I needed this lib for legacy project based on Django 1.9 and it didn't work. Here's the fix :slightly_smiling_face:

### CODE REVIEW

**Comment by riklaunim** [comment]
You can always use a previous version that did supported it. IF/ELSE may not guarantee full compatibility.

**Comment by dekoza** [comment]
Current version in `master` is mark(et)ed as supporting Django 1.8+ - I just helped it deliver the promise :wink: I also fixed the tests so I can prove that the lib with my fix works on Django 1.8+ Maybe I should configure Travis so that it'll actually use them :thinking:

**Comment by dekoza** [comment]
@riklaunim here you go :slightly_smiling_face:

**Comment by riklaunim** [comment]
nice :)

**Pull request merged**
