### PR TITLE
Scale down also height in the image browser

### PR DESCRIPTION
**Pull request by Tal500**
Add to the image browser template a code for scaling down height if needed.

### CODE REVIEW

**Review by matthiask — COMMENTED** [review]
You seem to be mixing spaces and tabs? Also, is there a reason for the two code blocks?

I think the code could be made clearer by using a pattern such as this one:
https://github.com/matthiask/django-imagefield/blob/1b866d65148cc87f249cb50b959e943734ca3af9/imagefield/processing.py#L103-L104

(I haven't tested the code at all and I'm not using the uploader, but I think the proposal makes sense.)

**Comment by Tal500** [comment]
> You seem to be mixing spaces and tabs? Also, is there a reason for the two code blocks?
> 
> I think the code could be made clearer by using a pattern such as this one: https://github.com/matthiask/django-imagefield/blob/1b866d65148cc87f249cb50b959e943734ca3af9/imagefield/processing.py#L103-L104
> 
> (I haven't tested the code at all and I'm not using the uploader, but I think the proposal makes sense.)

You right, my bad, just thought that admin should be notice this sketch of code...
Didn''t know what actually is preferred.

**Comment by Tal500** [comment]
> This pull request hasn't seen any activity for a long time and will soon be closed.

I think this should be fixed

**Comment by matthiask** [comment]
Yes, I'll merge the PR if you (or someone) addresses my comments. Thanks!

**Comment by matthiask** [comment]
I'm closing this because django-ckeditor is end of life, as is the open source version of CKEditor 4. See #761

**Comment by Tal500** [comment]
> I'm closing this because django-ckeditor is end of life, as is the open source version of CKEditor 4. See #761

Sorry to hear this bad news for the whole internet

**Comment by matthiask** [comment]
Yes, it's a bit sad but I also really understand the CKEditor developers point of view.

**Pull request closed without merging**
