### PR TITLE
Allow non-image files to be uploaded

### PR DESCRIPTION
**Pull request by simonpanay**
I reworked pull request #17 to allow non-image files to be uploaded.
It's far from perfect, but it works.
If you have any suggestions, please, tell me.

### CODE REVIEW

**Comment by n3storm** [comment]
This pull request has some important errors.

- utils.py line 13 static files URL is hardcoded
- views.py line 117 for loop in general is not behaving as expected because some times variable visible_filename wasn't initialized. I have recoded this:

```
    for filename in get_image_files(user=user):
        src = utils.get_media_url(filename)
        if getattr(settings, 'CKEDITOR_IMAGE_BACKEND', None):
            if is_image(src):
                thumb = utils.get_media_url(utils.get_thumb_filename(filename))
                visible_filename = None
            else:
                thumb = utils.get_icon_filename(filename)
                visible_filename = os.path.split(filename)[1]
                if len(visible_filename) > 20:
                    visible_filename = visible_filename[0:19] + '...'
        else:
            thumb = src
```

as this
```     
for filename in get_image_files(user=user):
        src = utils.get_media_url(filename)
        thumb = utils.get_icon_filename(filename)
        visible_filename = os.path.split(filename)[1]
        if len(visible_filename) > 20:
            visible_filename = visible_filename[0:19] + '...'
        if is_image(src):
            if getattr(settings, 'CKEDITOR_IMAGE_BACKEND', None):
                thumb = utils.get_media_url(utils.get_thumb_filename(filename))
            else:
                thumb = src
 ```
Plus, showing filename in all cases looks practical for differentiating similar files (for example, when only size or color depth changes but there is no visible change).

**Comment by martinkrung** [comment]
Can you merge this? I would like to use it in a project. Thanks..

**Comment by SalahAdDin** [comment]
:+1:  please, merge it.

**Comment by meriloi** [comment]
Can anyone merge it?

**Comment by riklaunim** [comment]
Yes, and then it will have to be released as a package... But I also want to split current app into two - ckeditor field application and file upload application. More and more features is put into the file management side than into ckeditor.

And also the image widget is getting old and may eventually die with newer ckeditor versions. (and it's hard for a replacement that wouldn't be for example PHP oriented).

**Comment by SalahAdDin** [comment]
I don't understand you.

**Pull request merged**
